POST http://localhost:8000/embed
Content-Type: application/json

{
  "texts": [
    "aaaa",
    "bbbb",
    "cccc"
  ]
}

###

POST http://localhost:8000/generate
Content-Type: application/json

{
  "prompt": "ddddd"
}

###

GET http://localhost:8000/output?ids=2&ids=3

